// Live testnet deploy + FULL cost-plus lifecycle of the flagship new instrument (murabaha),
// generated by deducible. Proves on a public network: qabd-before-sell (acquireAsset must precede
// sell), cost disclosure, and the buyer paying the fixed deferred total with the bank made whole.
// Testnet only. Reuses deploy_zakat_live.js patterns.
require("dotenv").config();
const fs = require("fs");
const path = require("path");
const {
  Client, AccountId, PrivateKey, Hbar,
  AccountCreateTransaction, AccountBalanceQuery,
  ContractCreateFlow, ContractFunctionParameters, ContractExecuteTransaction, ContractCallQuery,
} = require("@hashgraph/sdk");

function selectOperatorKey() {
  const want = (process.env.HEDERA_EVM_ADDRESS || "").trim().toLowerCase().replace(/^0x/, "");
  for (const v of ["HEDERA_OPERATOR_KEY", "HEDERA_HEX_PRIVATE_KEY", "HEDERA_DER_PRIVATE_KEY"]) {
    const raw = (process.env[v] || "").trim();
    if (!raw) continue;
    let k = null;
    for (const p of [() => PrivateKey.fromStringECDSA(raw), () => PrivateKey.fromStringDer(raw)]) {
      try { k = p(); break; } catch (e) {}
    }
    if (!k) continue;
    let evm = "";
    try { evm = k.publicKey.toEvmAddress().toLowerCase(); } catch (e) {}
    if (want && evm === want) return k;
  }
  throw new Error("no private key matches HEDERA_EVM_ADDRESS");
}
function artifact(name) {
  const root = path.join(__dirname, "..", "artifacts", "contracts");
  const stack = [root];
  while (stack.length) {
    const dir = stack.pop();
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      if (e.isDirectory()) stack.push(p);
      else if (e.name === name + ".json") return JSON.parse(fs.readFileSync(p, "utf8"));
    }
  }
  throw new Error("artifact not found: " + name);
}
async function mkAcct(payer, key, hbar) {
  let tx = new AccountCreateTransaction().setInitialBalance(new Hbar(hbar));
  tx = typeof tx.setKeyWithoutAlias === "function" ? tx.setKeyWithoutAlias(key.publicKey) : tx.setKey(key.publicKey);
  return (await (await tx.execute(payer)).getReceipt(payer)).accountId;
}
async function bal(client, id) {
  const b = await new AccountBalanceQuery().setAccountId(id).execute(client);
  return BigInt(b.hbars.toTinybars().toString());
}

async function main() {
  const COST = 1000000, MARKUP = 100000, TOTAL = COST + MARKUP; // tinybar
  const opKey = selectOperatorKey();
  const opId = AccountId.fromString(process.env.HEDERA_ACCOUNT_ID || process.env.HEDERA_OPERATOR_ID || "0.0.9301070");
  const bank = Client.forTestnet().setOperator(opId, opKey);
  bank.setDefaultMaxTransactionFee(new Hbar(20));

  // customer account (will pay the deferred total)
  const custKey = PrivateKey.generateECDSA();
  const custId = await mkAcct(bank, custKey, 1);
  // a non-aliased account calls contracts from its LONG-ZERO evm address (= toSolidityAddress),
  // which is what `msg.sender` will be — NOT the key-derived address. Use it for `customer`.
  const custEvm = custId.toSolidityAddress();
  const cust = Client.forTestnet().setOperator(custId, custKey);
  cust.setDefaultMaxTransactionFee(new Hbar(20));
  console.log("customer account:", custId.toString(), "0x" + custEvm);

  // deploy MurabahahGen(customer, cost, markup); bank = deployer
  const bytecode = artifact("MurabahahGen").bytecode.replace(/^0x/, "");
  const flow = new ContractCreateFlow().setBytecode(bytecode).setGas(3_000_000)
    .setConstructorParameters(new ContractFunctionParameters().addAddress(custEvm).addUint256(COST).addUint256(MARKUP));
  const cid = (await (await flow.execute(bank)).getReceipt(bank)).contractId;
  console.log("DEPLOYED MurabahahGen ->", cid.toString());

  const callU = async (fn) => (await new ContractCallQuery().setContractId(cid).setGas(60000).setFunction(fn).execute(bank)).getUint256(0).toString();
  const callB = async (fn) => (await new ContractCallQuery().setContractId(cid).setGas(60000).setFunction(fn).execute(bank)).getBool(0);
  console.log("on-chain total:", await callU("total"), "(expected", TOTAL + ")");

  const bankCall = async (fn) => { await (await new ContractExecuteTransaction().setContractId(cid).setGas(150000).setFunction(fn).execute(bank)).getReceipt(bank); };
  await bankCall("acquireAsset"); console.log("acquireAsset (qabd) ok; acquired =", await callB("acquired"));
  await bankCall("discloseCost"); console.log("discloseCost ok; disclosed =", await callB("disclosed"));
  await bankCall("sell");         console.log("sell ok; sold =", await callB("sold"));

  const bankBefore = await bal(bank, opId);
  await (await new ContractExecuteTransaction().setContractId(cid).setGas(150000)
    .setPayableAmount(Hbar.fromTinybars(TOTAL)).setFunction("payInstalment").execute(cust)).getReceipt(cust);
  const bankAfter = await bal(bank, opId);
  console.log("customer paid total; paid =", await callU("paid"), " settled =", await callB("settled"));
  console.log("bank balance delta (tinybar):", (bankAfter - bankBefore).toString(), "(~+" + TOTAL + " minus query fees)");

  const rec = {
    instrument: "murabahah", contract: "MurabahahGen", contractId: cid.toString(), network: "testnet",
    customer: custId.toString(), customerEvm: "0x" + custEvm,
    cost: COST, markup: MARKUP, total: Number(await callU("total")),
    acquired: await callB("acquired"), sold: await callB("sold"),
    paid: Number(await callU("paid")), settled: await callB("settled"),
    note: "Live deploy + full cost-plus lifecycle (qabd -> disclose -> sell -> pay) of a deducible-generated murabaha.",
  };
  fs.writeFileSync(path.join(__dirname, "..", "deployments", "testnet_murabahah.json"), JSON.stringify(rec, null, 2));
  console.log("record -> deployments/testnet_murabahah.json");
  await bank.close(); await cust.close();
}
main().then(() => process.exit(0)).catch((e) => { console.error("ERROR:", e.message || e); process.exit(1); });
